[BI-1144] correct parsing of scale value and scale label
Breeding-Insight/bi-api pull request #118
Opened 2021-11-29 21:17 UTC by davedrp

for https://breedinginsight.atlassian.net/browse/BI-1144

2021-11-30 03:12 UTC, timparsons approved these changes

2021-11-30 14:20 UTC, nickpalladino approved these changes

2021-11-30 16:40 UTC, timparsons commented
@davedrp Can you change the target branch for this PR to be `releases/0.4` please?

2021-11-30 16:40 UTC, timparsons requested changes
Needs to be merged to `releases/0.4`

2021-12-02 16:21 UTC, timparsons approved these changes

2021-12-02 17:13 UTC, merged