[BI-1251] - Germplasm import: fix to post order construction
Breeding-Insight/bi-api pull request #128
Opened 2021-12-13 21:55 UTC by ctucker3

Germplasm were being POSTed twice because of bug in the post order construction. 

See sgn BI-1251 for card details: https://github.com/Breeding-Insight/sgn/pull/48

2021-12-20 17:33 UTC, dmeidlin approved these changes

2021-12-22 22:27 UTC, timparsons requested changes
Maybe this should be in a different card, but when I was testing this, I uploaded two files (referenced in https://github.com/Breeding-Insight/sgn/pull/48).  When the second one was uploaded, the preview did not show the pedigree string on the preview table.  I went ahead and did the save, and pulling the data back via BrAPI has all the correct pedigree info.

2021-12-23 15:06 UTC, ctucker3 commented
> Maybe this should be in a different card, but when I was testing this, I uploaded two files (referenced in [Breeding-Insight/sgn#48](https://github.com/Breeding-Insight/sgn/pull/48)). When the second one was uploaded, the preview did not show the pedigree string on the preview table. I went ahead and did the save, and pulling the data back via BrAPI has all the correct pedigree info.

Tim and I tried again on his machine and this was no longer an issue.

2021-12-23 16:02 UTC, timparsons approved these changes

2021-12-23 17:57 UTC, merged