[BI-1056] GET germplasm override
Breeding-Insight/bi-api pull request #130
Opened 2022-01-05 16:00 UTC by ctucker3

# Description
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1056

Overrides the brapi proxy for GET germplasm and makes the following changes to the response:
- Assigns breedingMethodDbId the value of additionalInfo->breedingMethodId
- Removes [<program key>-<accessionNumber>] from the germplasm name
- Changes pedigree string from <female parent name>/<male parent name> to <female parent GID>/<male parent GID>
- Fixes a small pagination bug 
- Fixes sorting on the backend so it is now alphanumeric.

# Dependencies
bi-web : BI-1056
sgn: BI-1056

# Testing
See bi-web: BI-1056 for testing details.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF.

2022-01-06 20:22 UTC, timparsons requested changes

2022-01-10 14:41 UTC, ctucker3 commented on src/main/java/org/breedinginsight/brapi/v2/GermplasmController.java
> +        String respBody = gson.toJson(response);
Added a JsonSerializer

2022-01-10 14:41 UTC, ctucker3 commented on src/main/java/org/breedinginsight/brapi/v2/model/response/mappers/GermplasmQueryMapper.java
> +        else throw new NullPointerException();
Changed

2022-01-10 14:41 UTC, ctucker3 commented on src/main/java/org/breedinginsight/brapi/v2/services/BrAPIGermplasmService.java
> +            throw new InternalServerException(e.getMessage());
Changed

2022-01-10 19:04 UTC, timparsons requested changes

2022-01-10 19:04 UTC, timparsons commented on src/main/java/org/breedinginsight/brapi/v2/GermplasmController.java
> +    private Gson gson;
I don't think this is needed anymore

2022-01-10 19:09 UTC, ctucker3 commented on src/main/java/org/breedinginsight/brapi/v2/GermplasmController.java
> +    private Gson gson;
removed

2022-01-10 19:15 UTC, timparsons approved these changes

2022-01-10 21:08 UTC, davedrp approved these changes

2022-01-12 15:09 UTC, merged