[BI-1088] Germplasm List Download
Breeding-Insight/bi-api pull request #143
Opened 2022-01-28 21:36 UTC by HMS17

# Description
**Story:** [BI-1088 - Germplasm List Export File](https://breedinginsight.atlassian.net/browse/BI-1088)

_Please include a summary of the change that was made._

# Dependencies
bi-web/BI-1088

# Testing
_Please include any details needed for reviewers to test this code_

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2022-02-09 15:44 UTC, dmeidlin commented on src/main/java/org/breedinginsight/brapps/importer/daos/BrAPIListDAO.java
> +        listSearch.addListDbIdsItem(listId);
It looks like `listSearch` isn't used and can be removed.

2022-02-09 16:07 UTC, dmeidlin approved these changes

2022-02-09 17:32 UTC, davedrp requested changes
**STEPS**
1) uploaded [Missing_1_male_eNo.xls](https://github.com/Breeding-Insight/bi-api/files/8034860/Missing_1_male_eNo.xls) (row 3 has a **Female Parent Entry No** but no **Male Parent Entry No**)
_NOTE: Shawn says that having only a female parent is valid.  She says:_
>  If germplasm is cloned, the parent is considered the mother (even if it gender of the individual  is hermaphroditic or male)

2)Tried to download the data.

**OUTCOME**:
A new tab was open with the message:
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

**EXPECTED**
A) the download list xsl
-also -
B) If there is an error, then a more user-friendly error message.

2022-02-15 16:09 UTC, HMS17 commented
> ### Second failed Test
> **STEPS**
> 
> 1. uploaded [pedigree_by_GID_small.xls](https://github.com/Breeding-Insight/bi-api/files/8043904/pedigree_by_GID_small.xls)(has **Female Parent GID**  and **Male Parent GID**)
> 
> 2)Tried to download the data.
> 
> **OUTCOME**: A new browser tab was open with the message: `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`
> 
> **EXPECTED** A) the download list xsl

Tests should be passing now

2022-02-15 16:50 UTC, davedrp approved these changes

2022-02-15 17:04 UTC, merged