[BI-1397] Breeding methods: update breeding method db entries
Breeding-Insight/bi-api pull request #159
Opened 2022-03-07 15:50 UTC by ctucker3

# Description
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1397

Fixed breeding methods to match Shawn's specification. https://breedinginsight.atlassian.net/wiki/spaces/BI/pages/1554907145/Breeding+Methods+Validations

# Dependencies
bi-web: BI-1397

# Testing
1. Download the template from the germplasm import page and verify the changes in the JIRA card are reflected. 
2. Create a germplasm import that uses all of the breeding method codes and names from Shawn's specification: https://breedinginsight.atlassian.net/wiki/spaces/BI/pages/1554907145/Breeding+Methods+Validations
3. Import file and ensure there are no errors. 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2022-03-07 19:07 UTC, timparsons requested changes

2022-03-07 19:07 UTC, timparsons commented on src/main/resources/db/migration/V0.5.33__alter-breeding-methods.sql
> +update breeding_method set name = 'Collected (landrace)' where abbreviation = 'LDR';
The bug references that "Landrace" doesn't work in the file.  Should the entry in bidb be "Landrace" or "Collected (landrace)"? (maybe this is better asked of @shawnyarnes)

2022-03-08 14:05 UTC, timparsons approved these changes

2022-03-08 15:12 UTC, dmeidlin approved these changes

2022-03-08 15:35 UTC, merged