[BI-1417] - Handle NA pedigree strings from Breedbase
Breeding-Insight/bi-api pull request #165
Opened 2022-03-24 17:46 UTC by HMS17

# Description
**Story:** [BI-1417 - Handle NA pedigree strings from Breedbase](https://breedinginsight.atlassian.net/browse/BI-1417)

Added logic to set display parent GID to null when breedbase returns "NA" for pedigree information.

# Dependencies
bi-web/release/0.5

# Testing
Import germplasm file with rows with no parents, one parent, and two parents. Ensure that parents GIDs are still displayed properly and no NA displays for Breedbase programs.

(Germplasm export functionality will be tested with BI-1088)

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have tested my code and ensured it meets the acceptance criteria of the story
- [n/a] I have create/modified unit tests to cover this change
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2022-03-28 18:46 UTC, timparsons requested changes

2022-03-28 18:46 UTC, timparsons commented on src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIGermplasmDAO.java
> +                        parents = new ArrayList<>();
I think this fix also needs to be applied to the block below if there are two parents (starts on line 152)

2022-03-28 19:45 UTC, timparsons approved these changes

2022-03-29 13:24 UTC, ctucker3 approved these changes

2022-03-29 14:49 UTC, merged