[BI-1446] trait error: fix error display on trait form
Breeding-Insight/bi-api pull request #190
Opened 2022-06-10 14:32 UTC by ctucker3

# Description
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1366

The trait errors were accidentally changed when making the trait file import names more consistent. (https://github.com/Breeding-Insight/bi-api/pull/150/files#diff-645879ab06ebc8d8a2f7b0272aaf4c5e897cb743c52798982139924349f1235f)

Reversed those changes for the trait form code, but kept the fixes to the trait file import code. 

# Dependencies
biweb: develop

# Testing
1. Go to the trait list
2. Click on "New Trait"
3. Check that the errors are displayed below the fields. 
4. Try out the Computation, Ordinal, and Nominal fields. 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have tested that my code works with both the brapi-java-server and BreedBase
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<please include a link to TAF run>_

2022-06-10 22:22 UTC, HMS17 requested changes
Looks like it's working locally. Have you run it against TAF? Since a decent portion of the remaining TAF failures were related to these error messages being missing.

2022-06-10 22:23 UTC, HMS17 commented
Also the wrong card is linked in the PR description.

2022-06-13 19:26 UTC, ctucker3 commented
@HMS17 I ran TAF and it looks like it fixes 3 tests that were previously failing. The remaining 3 tests look to be failing because an accessor method error.

2022-06-13 19:32 UTC, HMS17 approved these changes

2022-06-14 15:04 UTC, nickpalladino approved these changes

2022-06-14 15:45 UTC, merged