BI-1555 - Cache program ontology terms
Breeding-Insight/bi-api pull request #206
Opened 2022-08-18 22:27 UTC by timparsons

# Description
**Story:** https://breedinginsight.atlassian.net/browse/BI-1555

- Modified the underlying cache storage from in memory of the running application to now being stored in Redis.  
- Added the Redisson client library
- Modified the `ProgramCache` to utilize Redis instead of Guava's `LoadingCache`.
- Implemented caching for the `TraitDAO`

# Dependencies
Redis container -> this has been added to the `docker-compose.yml` file in bi-api, so you should be able to start up that container, and the code will default to `localhost:6379` to look for a Redis server to connect to.

# Testing
Test traits:
1. Start up bi-api and wait for a log message like `cache loading complete for key: <programUUID>:trait` (you may want to wait until you see your program UUID of interest)
2. navigate to the ontology terms page, and ensure the traits load (hopefully faster)

Test germplasm:
1. Start up bi-api and wait for a log message like `cache loading complete for key: <programUUID>:brapigermplasm` (you may want to wait until you see your program UUID of interest)
2. navigate to the all germplasm page, and ensure the germplasm records load (hopefully faster)

Test restart (records should persist in redis between bi-api restarts):
1. start bi-api and let the cache load
2. restart bi-api, and refresh the germplasm or trait list page immediatly after the server successfully starts up
3. ensure the page loads with all the appropriate records

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [x] I have tested that my code works with both the brapi-java-server and BreedBase
- [x] I have create/modified unit tests to cover this change
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<please include a link to TAF run>_

2022-09-13 17:42 UTC, HMS17 requested changes
Testing locally revealed some problems.

Brapi:

- **Single trait add errors**
- **Batch trait import errors**
- Batch germplasm import passes
- Germplasm table display passes
- Germplasm list table display passes
- Germplasm export passes 

BB:

- First single trait add passes
- **Second single trait add "passes" but doesn't display
- Batch trait import "passes" but doesn't display and neither does second single trait. Traits do not display after waiting and refreshing, but do display once bi-api is restarted**
- Batch germplasm import passes and germplasm displayed for two separate imports
- **Displaying germplasm lists errors**

2022-09-14 14:52 UTC, davedrp commented
Developer Testing failed - 
**Steps to reproduce**
1) viewed Ontology list (42-ontologies were present)
2) Import 3-ontologies.
3) clear browser cash
4) viewed Ontology list

**Expected result**
Ontology list has 45-ontologies (The original 42 plus the 3 new ontologies).

**Actual result**
Only the original 42-ontologies were present.  The 3 new ontologies were not present.

**NOTE**
if the bi-api server was restarted, and the Ontology list was viewed, the  3 new ontologies were not present.

2022-09-14 14:54 UTC, davedrp requested changes
developer-test failed

2022-09-15 16:34 UTC, davedrp approved these changes

2022-09-15 16:35 UTC, davedrp commented
passed my Developer testing

2022-09-21 14:22 UTC, HMS17 approved these changes
Tests passed!

Brapi:
* Single trait add passes
* Batch trait import passes
* Batch germplasm import passes
* Germplasm table display passes
* Germplasm list table display passes
* Germplasm export passes

BB:
* First single trait add passes
* Second single trait add passes
* Batch trait import passes
* Batch germplasm import passes and germplasm displayed for two imports
* Displaying germplasm lists errors - but error also shows up in qa-test

2022-09-27 20:30 UTC, timparsons commented on src/main/java/org/breedinginsight/daos/impl/TraitDAOImpl.java
> +        //TODO: Need to roll back somehow if there is an error
NA, was a pre-existing TODO

2022-09-27 20:30 UTC, timparsons commented on src/main/java/org/breedinginsight/daos/impl/TraitDAOImpl.java
> +        // TODO: If there is a failure after the first brapi service, roll back all before the failure.
NA, was a pre-existing TODO

2022-09-27 20:30 UTC, timparsons commented on src/main/java/org/breedinginsight/daos/impl/TraitDAOImpl.java
> +        //TODO: Pass ontology reference
NA, was a pre-existing TODO

2022-09-27 20:30 UTC, timparsons commented on src/main/java/org/breedinginsight/daos/impl/TraitDAOImpl.java
> +        // TODO: make sure have all expected external references
NA, was a pre-existing TODO

2022-09-27 20:30 UTC, timparsons commented on src/main/java/org/breedinginsight/daos/impl/TraitDAOImpl.java
> +        // TODO: make sure have all expected external references
NA, was a pre-existing TODO

2022-09-27 20:30 UTC, timparsons commented on src/main/java/org/breedinginsight/daos/impl/TraitDAOImpl.java
> +//        Map<UUID, Trait> dbVariablesMap = dbVariables.stream().collect(Collectors.toMap(Trait::getId, p -> p));
Removed

2022-09-27 20:31 UTC, timparsons commented on src/main/java/org/breedinginsight/daos/impl/ProgramDAOImpl.java
> +        // TODO: If there is a failure after the first brapi service, roll back all before the failure.
NA, was a pre-existing TODO

2022-09-27 20:31 UTC, timparsons commented on src/main/java/org/breedinginsight/daos/impl/ProgramDAOImpl.java
> +            //TODO: Need to add archived/not archived when available in brapi
NA, was a pre-existing TODO

2022-09-27 20:32 UTC, timparsons commented on src/main/java/org/breedinginsight/daos/impl/ProgramDAOImpl.java
> +    //TODO figure out why BrAPIServiceFilterIntegrationTest fails when requestTimeout is set in the constructor
NA, was a pre-existing TODO

2022-09-27 20:49 UTC, merged