update import service
Breeding-Insight/bi-api pull request #247
Opened 2023-04-03 16:10 UTC by dmeidlin

# Description
**Story:** _Please include a link to the story in Jira_

_Please include a summary of the change that was made._

# Dependencies
_Please include any dependencies to other code branches, testing configurations, scripts to be run, etc._

# Testing
_Please include any details needed for reviewers to test this code_

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have tested that my code works with both the brapi-java-server and BreedBase
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<please include a link to TAF run>_

2023-04-27 21:03 UTC, timparsons requested changes

2023-04-27 21:03 UTC, timparsons commented on src/main/java/org/breedinginsight/utilities/BrAPIDAOUtil.java
> +            log.warn(Utilities.generateApiExceptionLogMessage(e));
This should use `log.error`

2023-05-01 16:57 UTC, davedrp requested changes

2023-05-02 15:32 UTC, davedrp approved these changes

2023-05-08 17:29 UTC, timparsons approved these changes
Looks good! Approving assuming the commented out code is removed.

2023-05-08 17:29 UTC, timparsons commented on src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java
> +        //existingTrial.setTrialName(Utilities.removeProgramKey(existingTrial.getTrialName(), program.getKey()));
Can this line be removed?

2023-05-10 16:35 UTC, merged