BI-1855 - Create germplasm list not working
Breeding-Insight/bi-api pull request #281
Opened 2023-08-08 15:24 UTC by nickpalladino

# Description
**Story:** [BI-1855](https://breedinginsight.atlassian.net/browse/BI-1855?atlOrigin=eyJpIjoiMmMzMzdmMjMyOGYzNDY4OGI5NjhjMDljNDc3MzAxMjEiLCJwIjoiaiJ9)

- Germplasm update logic changed:
- Allow empty pedigree values to enable creating a new germplasm list without requiring the original pedigree values
- Only require parent gids to be entered when updating a germplasm pedigree rather than gid and entry number
- Various bug fixes found when testing against Breedbase

# Dependencies
- release/0.8 bi-web

# Testing
- Test different combinations of updating pedigrees, synonyms, and not allowed pedigree changes
- Test files used in development, number indicates order ascending: [1855-tep46-np398.zip](https://github.com/Breeding-Insight/bi-api/files/12315658/1855-tep46-np398.zip)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [x] I have tested that my code works with both the brapi-java-server and BreedBase
- [ ] I have create/modified unit tests to cover this change
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<please include a link to TAF run>_

[BI-1855]: https://breedinginsight.atlassian.net/browse/BI-1855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-08-14 15:09 UTC, mlm483 requested changes
Getting a `NullPointerException`. To reproduce, try to upload the attached germplasm file. It works on `develop` but on `bug/BI-1855-tep46` I get a `NullPointerException` during the "Upload and Validate" process.

[100 Germplasm.xlsx](https://github.com/Breeding-Insight/bi-api/files/12336444/100.Germplasm.xlsx)

2023-08-15 17:18 UTC, davedrp commented
TESTING
senario: has existing pedigree and file pedigree is different and not empty.
result: showed error.
PASSED

senario: no existing pedigree and file different pedigree.
result: no error.
PASSED


senario: existing pedigree and file pedigree samee.
result: no error.
PASSED


senario: existing pedigree and file pedigree empty.
result: no error.
PASSED

2023-08-15 17:21 UTC, davedrp commented
The code and logic seem great to me.  I left some comments on minor cosmetic changes.

2023-08-15 17:22 UTC, davedrp requested changes
The code and logic seem great to me. I left some comments on minor cosmetic changes.

2023-08-15 20:58 UTC, nickpalladino commented
> Getting a `NullPointerException`. To reproduce, try to upload the attached germplasm file. It works on `develop` but on `bug/BI-1855-tep46` I get a `NullPointerException` during the "Upload and Validate" process.
> 
> [100 Germplasm.xlsx](https://github.com/Breeding-Insight/bi-api/files/12336444/100.Germplasm.xlsx)

Pushed a fix for this

2023-08-16 13:51 UTC, nickpalladino commented on src/main/java/org/breedinginsight/brapps/importer/model/base/Germplasm.java
> +    public boolean pedigreesEqualGidOnly(BrAPIGermplasm brAPIGermplasm) {
Nope, I removed it and pushed changes

2023-08-16 13:51 UTC, nickpalladino commented on src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java
> +import org.brapi.v2.model.BrAPIAcceptedSearchResponse;
Removed and pushed changes

2023-08-16 19:33 UTC, mlm483 approved these changes
Thanks for the test files, super helpful!

___

The file `3_new list-wrongped - fail.xls` is expected to produce an error, but I noticed it says "See details below" when there are no details to be seen below. Possibly out of scope, but I recommend either (1) providing details in this error case or (2) if it's truly exceptional, removing "See details below".  Could make a new story.

![image](https://github.com/Breeding-Insight/bi-api/assets/128052931/11208ec4-b2f5-4718-b6c1-cd297f90152f)

FWIW I'm seeing "The following parental GIDs were not found in the database: 5, 6, 7, 8." being sent from the server, so it might be as simple as showing that message on the frontend.
 
___

Here's the story I created to refactor processGermplasmForDisplay, [BI-1881](https://breedinginsight.atlassian.net/browse/BI-1881).

___

Assuming the `missingParentalDbIds` and `missingDbIds` business is sorted out and you feel good about it, I'm OK to merge.

2023-08-17 20:55 UTC, nickpalladino commented on src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIGermplasmDAO.java
> +    private String processBreedbasePedigree(String pedigree) {
I created a story [BI-1883](https://breedinginsight.atlassian.net/browse/BI-1883?atlOrigin=eyJpIjoiOGE5ZmY4NTliNzE4NDZhY2EzZDExYzk1NzI3YmQ2YmQiLCJwIjoiaiJ9) and updated the comment.

2023-08-17 20:55 UTC, nickpalladino commented on src/main/java/org/breedinginsight/brapi/v2/dao/BrAPIGermplasmDAO.java
> +                additionalInfo.addProperty(BrAPIAdditionalInfoFields.GERMPLASM_RAW_PEDIGREE, pedigree);
Added a comment

2023-08-18 03:25 UTC, nickpalladino commented on src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java
> +        List<String> missingDbIds = germplasmDBIDs.entrySet().stream().filter(Map.Entry::getValue).map(Map.Entry::getKey).collect(Collectors.toList());
I looked into this more and did some testing. I ended up changing `List<String> missingDbIds = germplasmDBIDs.entrySet().stream().filter(Map.Entry::getValue).map(Map.Entry::getKey).collect(Collectors.toList());` to `List<String> missingDbIds = germplasmDBIDs.entrySet().stream().filter(entry -> !entry.getValue()).map(Map.Entry::getKey).collect(Collectors.toList());`. The map is setup with values of true for parent gids and false for update gids. So now these lists are filtered appropriately from the map and will have different values.

2023-08-18 03:28 UTC, nickpalladino commented on src/main/java/org/breedinginsight/brapps/importer/services/processors/GermplasmProcessor.java
> +                                          String.format(missingDbIdsMsg,
With the change that has been made this has been resolved.

2023-08-18 13:53 UTC, merged