BI-1911 fix QA findings
Breeding-Insight/bi-api pull request #304
Opened 2023-10-20 16:11 UTC by davedrp

# D# Description
[BI-1911](https://breedinginsight.atlassian.net/browse/BI-1911) - in response to Shahana's [testing notes.](https://breedinginsight.atlassian.net/browse/BI-1911?focusedCommentId=14057)

# Dependencies
bi-api: bug/BI-1911-2 branch

# Testing
- Import an Experiment.
- Look at the confirmation page.

**Expected Results**
- The `Env Year`, `Env`, and  `Exp unit ID` columns should appear as they did in the import file.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [x] I have run TAF: _\<link to TAF run>_

[BI-1911]: https://breedinginsight.atlassian.net/browse/BI-1911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQescription
[BI-1911](https://breedinginsight.atlassian.net/browse/BI-1911) - in response to Shahana's [testing notes.](https://breedinginsight.atlassian.net/browse/BI-1911?focusedCommentId=14057)

# Dependencies
bi-web: bug/BI-1911-2 branch

# Testing
- Import an Experiment.
- Look at the confirmation page.

**Expected Results**
- The `Env Year`, `Env`, and  `Exp unit ID` columns should appear as they did in the import file.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [x] I have run TAF: _\<link to TAF run>_

[BI-1911]: https://breedinginsight.atlassian.net/browse/BI-1911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-10-20 18:16 UTC, timparsons approved these changes

2023-10-20 19:33 UTC, mlm483 requested changes
Functionality looks good, I would make this change: https://github.com/Breeding-Insight/bi-web/pull/341#discussion_r1367420730

2023-10-30 13:45 UTC, davedrp commented
A new [story](https://breedinginsight.atlassian.net/browse/BI-1973) to address the [comment from MLM483](https://github.com/Breeding-Insight/bi-api/pull/304#pullrequestreview-1690800978) has been written.

2023-10-30 13:51 UTC, mlm483 approved these changes

2023-10-30 15:02 UTC, merged