BI-2045 (Failure to report error when uploading duplicated experiment name)
Breeding-Insight/bi-api pull request #333
Opened 2024-02-19 17:54 UTC by davedrp

# Description
[BI-2045](https://breedinginsight.atlassian.net/browse/BI-2045) (Failure to report error when uploading duplicated experiment name)

# Dependencies
_Please include any dependencies to other code branches, testing configurations, scripts to be run, etc._

# Testing
Successfully import an experiment.
Attempt to import the same experiment file (with no ObsUnitIDs).
**EXPECTED RESULT**
- The banner message `Error detected in file, XXX.xls. Experiment Title already exists. Import cannot proceed.`

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have tested my code and ensured it meets the acceptance criteria of the story
- [X] I have tested that my code works with both the brapi-java-server and BreedBase
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<please include a link to TAF run>_

2024-02-20 13:47 UTC, mlm483 approved these changes
Tested, working.

2024-02-20 15:34 UTC, dmeidlin approved these changes

2024-03-04 19:02 UTC, dmeidlin commented on src/main/java/org/breedinginsight/brapps/importer/services/processors/ExperimentProcessor.java
> +                throw new UnprocessableEntityException(PREEXISTING_EXPERIMENT_TITLE);
A possible NPE if line 1181 returns null can be avoided 
```suggestion
            if  (trialPio != null && ImportObjectState.EXISTING == trialPio.getState() && (StringUtils.isBlank( importRow.getObsUnitID() )) && (envPio!=null && ImportObjectState.EXISTING==envPio.getState() ) ){
                throw new UnprocessableEntityException(PREEXISTING_EXPERIMENT_TITLE);
```

2024-03-04 19:04 UTC, dmeidlin commented on src/test/java/org/breedinginsight/brapps/importer/ExperimentFileImportTest.java
> +    public void importNewExpMultiNewEnvError() {
This test asserts that both environments import successfully, so it's not clear to me why the test name needs to change to include "Error".

2024-03-04 19:05 UTC, dmeidlin requested changes
Just a couple of small points, otherwise looks good.

2024-03-04 19:55 UTC, mlm483 approved these changes
Tested, working. 🚀

2024-03-04 20:34 UTC, davedrp commented on src/test/java/org/breedinginsight/brapps/importer/ExperimentFileImportTest.java
> +    // NO Longer needed, but may be needed in the future.
The suggestions have been implemented

2024-03-04 20:37 UTC, dmeidlin approved these changes

2024-03-05 14:43 UTC, merged