[BI-2343] - GID filtering not informative
Breeding-Insight/bi-api pull request #435
Opened 2024-11-19 21:53 UTC by HMS17

# Description
**Story:** [BI-2343 - GID filtering not informative](https://breedinginsight.atlassian.net/browse/BI-2343)

Changes to enable exact match GID filtering for multiple tables

For Experiment Details and Sample Submission Details tables, frontend search is used, so a custom-search function was added in the respective buefy files to do exact search filtering in the GID case.

For Germplasm and Germplasm list tables, backend search is used, which presently only does partial matching. Due to the high risk associated with modifying backend search to alternatively enable exact or partial match for each filter, ResponseUtils:search was slightly modified to do an exact match specifically when the filter is accessionNumber.

# Dependencies
bi-web: bug/BI-2343

# Testing
see bi-web

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have tested that my code works with both the brapi-java-server and BreedBase
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<please include a link to TAF run>_

2024-11-21 21:10 UTC, mlm483 approved these changes

2024-11-22 14:28 UTC, davedrp requested changes
FAILED TESTING.
Everything looks great and behaves perfectly.  But, I did find one numeric column that has been overlooked.

If you navigate to Germplam > List > Details you’ll get something like:
<img width="797" alt="Screenshot 2024-11-22 at 9 18 27 AM" src="https://github.com/user-attachments/assets/c7642173-b876-4a5e-a9a0-7407b92d19aa">

**The filter for `Entry Number`  use the exact numerical match.**

2024-11-26 17:13 UTC, HMS17 commented
> FAILED TESTING. Everything looks great and behaves perfectly. But, I did find one numeric column that has been overlooked.
> 
> If you navigate to Germplam > List > Details you’ll get something like: <img alt="Screenshot 2024-11-22 at 9 18 27 AM" width="797" src="https://private-user-images.githubusercontent.com/7815559/388967689-c7642173-b876-4a5e-a9a0-7407b92d19aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDE0NjEsIm5iZiI6MTczMjY0MTE2MSwicGF0aCI6Ii83ODE1NTU5LzM4ODk2NzY4OS1jNzY0MjE3My1iODc2LTRhNWUtYTlhMC03NDA3YjkyZDE5YWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjZUMTcxMjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTEwZDA5NjQwMmExZWU5YmRkOTczZDhhMDQyNThjYTdiYmY5NTM4YjE4MDA3NGNjZTFlN2M1MGQwNmQxN2NjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WGqwBzuJQYos1Uek6FhStepIwvlMtszoj3fIZGRlaAs">
> 
> **The filter for `Entry Number` use the exact numerical match.**

Added exact match for entry number

2024-11-26 21:09 UTC, davedrp approved these changes

2024-11-27 16:14 UTC, merged