BI-2376 - Create Delete Endpoint for Deltabreed Experiment Controller
Breeding-Insight/bi-api pull request #437
Opened 2024-11-22 19:47 UTC by mlm483

# Description
**Story:** [BI-2376](https://breedinginsight.atlassian.net/browse/BI-2376)

# Dependencies
_Please include any dependencies to other code branches, testing configurations, scripts to be run, etc._

# Testing
_Please include any details needed for reviewers to test this code_

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have tested that my code works with both the brapi-java-server and BreedBase
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<please include a link to TAF run>_

2025-01-14 15:49 UTC, HMS17 requested changes
Looks good and nicely commented! My only concerns are a couple of todos that are unclear if they were meant to be addressed in this card or another.

2025-01-14 17:29 UTC, mlm483 commented on src/main/java/org/breedinginsight/brapi/v2/dao/BrAPICachedDAO.java
> +        // TODO: test calling populate alone (without invalidate first).
Thanks for catching this, I removed the comment. I was investigating it, but decided it would be a bad idea to call `populate` without calling `invalidate` first because the call to `populate` could potentially take some time to fetch fresh data, during which time someone could read invalid data. Calling invalidate is quick and cheap and mitigates the risk of reading stale data.

2025-01-14 17:30 UTC, mlm483 commented on src/main/java/org/breedinginsight/brapi/v2/dao/impl/BrAPITrialDAOImpl.java
> +        this.programExperimentCache.invalidate(programId);
See my response to your original comment on BrAPICachedDAO.java.

2025-01-14 20:31 UTC, HMS17 approved these changes

2025-01-15 15:54 UTC, davedrp approved these changes

2025-01-15 16:05 UTC, merged