BI-299 - Update application-prod.yml to define the web host (instead of loginSuccess/loginFailure/logout)
Breeding-Insight/bi-api pull request #45
Opened 2020-10-02 16:36 UTC by nickpalladino

## Changes
- Updated application.yml, application-prod.yml and added placeholder in .env

2020-10-05 20:07 UTC, nickpalladino commented
Not really sure what's going on with the build failing. @ctucker3 have you seen something like this?

2020-10-06 03:58 UTC, timparsons approved these changes

2020-10-06 15:07 UTC, ctucker3 requested changes
Can you add the WEB_BASE_URL to the .env file?

2020-10-06 15:38 UTC, nickpalladino commented
> Can you add the WEB_BASE_URL to the .env file?

Yep, added and pushed changes.

2020-10-06 16:11 UTC, ctucker3 approved these changes

2020-10-07 01:38 UTC, merged